create table userStatus
(
	ID int not null PRIMARY KEY IDENTITY(1,1),
	name varchar(8) NOT NULL check (name IN ('Pending', 'Active', 'Blocked'))
)

ALTER TABLE USERSTATUS
ADD UNIQUE (NAME)

INSERT INTO USERSTATUS VALUES ('PENDING')
INSERT INTO USERSTATUS VALUES ('ACTIVE')
INSERT INTO USERSTATUS VALUES ('BLOCKED')

SELECT * FROM USERSTATUS
INSERT INTO USERSTATUS VALUES ('BLOCK')